### PR TITLE
Switch to python 3. Build packages using AlmaLinux 8 and 9. Prepare new release.

### LINKED ISSUE #2: Python 3 compatibility
Hello.
Is there any plan to port glue-validator to Python 3? Python 2 EOL is near - January 2020.

Thank you.

### LINKED ISSUE #3: Build for CentOS 8
Build for CentOS 8, to be pushed to UMD.
Available in UMD4 for CentOS 7: http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/base/.

### LINKED ISSUE #6: Fix package building
Package building was added via #4, but building https://github.com/EGI-Federation/glue-validator/releases/tag/v2.0.25 failed as reported in https://github.com/EGI-Federation/glue-validator/actions/runs/4302754339.
I'm adding screenshots as logs will disappear after some time.
Screenshot 2023-03-01 at 12 15 39
Screenshot 2023-03-01 at 12 16 12
Screenshot 2023-03-01 at 12 16 09
Screenshot 2023-03-01 at 12 16 00

### PR DESCRIPTION
**Pull request by gwarf**
Switch to python3. Fix #2.
Build packages using AlmaLinux 8 and 9. Prepare new release. Fix #6. Fix #3.

```markdown
## [2.1.0] - 2023-03-17

### Added

- Build and release packages using AlmaLinux 8 and 9. (#7) (Baptiste Grenier)

### Changed

- Switch to python3. (#7) (Enol Fernandez)

### Fixed

- Fix tests. (#7) (Enol Fernandez)
```

### CODE REVIEW

**Comment by gwarf** [comment]
@enolfc, @andrea-manzi in case you are interested/have time/would like to look at something else, there are some python files here needing some love for moving to python3... 😇

**Comment by enolfc** [comment]
> @enolfc, @andrea-manzi in case you are interested/have time/would like to look at something else, there are some

Do you want to fix this for this PR? I have passed black through all of them and basically they get quite a reformatting.

**Comment by gwarf** [comment]
I think it's fine to do it in this PR. But if you prefer you can create another one, I will rebase.
I was also unsure about the implementations of all the type checks in `lib/*/types.py`, did you also look into this?

**Comment by enolfc** [comment]
linter is happy, I'm happy 😆 

but it seems my last change introduced some issues... debugging

**Comment by gwarf** [comment]
Great, thanks!
Can you also look at the test report?

**Comment by gwarf** [comment]
So the test of `ldif/GLUE2AdminDomain/AdminDomain.ldif` is failing with two errors:
```shell
✦2 ❯ ../bin/glue-validator -f ldif/GLUE2AdminDomain/AdminDomain.ldif -v 3
CRITICAL - errors 2, warnings 2, info 0 | errors=2;warnings=2;info=0
AssertionError: False is not true : ERROR START:
E025 Description: GLUE Schema object hierarchy violation
E025 Affected DN: NA                  
E025 Affected attribute: GLUE2Domain published
E025 Published value: GLUE2Location missing 

ERROR START:
E025 Description: GLUE Schema object hierarchy violation
E025 Affected DN: NA
E025 Affected attribute: GLUE2Domain published
E025 Published value: GLUE2Contact missing  

AssertionError: False is not true : WARNING START:
W034 Description: Mandatory attribute not present
W034 Affected DN: GLUE2DomainId=mysite.com 
                  o=GLUE
W034 Affected attribute: GLUE2DomainID
W034 Published value: NA 

WARNING START:
W034 Description: Mandatory attribute not present
W034 Affected DN: GLUE2DomainId=mysite.com 
                  o=GLUE
W034 Affected attribute: GLUE2DomainName
W034 Published value: NA
```

So errors due to missing `GLUE2Location` and `GLUE2Contact` attributes when object is a `GLUE2Domain`.
But technically this is not in accordance with [GLUE 2.0](https://redmine.ogf.org/dmsf/glue-wg6ff7.html?folder_id=18) or the [GLUE 2.1 draft](https://docs.ogf.org/glue-2-1-test/):
Screenshot 2023-03-23 at 17 24 58

But this was added on purpose to address a bug in an inaccessible bug tracker: https://github.com/EGI-Federation/glue-validator/commit/0aca90cf144595088e00af4b6691a9a8bb1deb84

So maybe we could add the missing objects to the tests, and document in the code that while it's breaking/not following the spec, it was added on purpose (even if we are not sure why, I guess it was making sense to ensure that we have a contact + location)?

And we could likely ignore the warnings.

@paolini78 any opinion on this?

**Comment by enolfc** [comment]
> So the test of `ldif/GLUE2AdminDomain/AdminDomain.ldif` is failing with two errors:
> 
> ```shell
> ✦2 ❯ ../bin/glue-validator -f ldif/GLUE2AdminDomain/AdminDomain.ldif -v 3
> CRITICAL - errors 2, warnings 2, info 0 | errors=2;warnings=2;info=0
> AssertionError: False is not true : ERROR START:
> E025 Description: GLUE Schema object hierarchy violation
> E025 Affected DN: NA                  
> E025 Affected attribute: GLUE2Domain published
> E025 Published value: GLUE2Location missing 
> 
> ERROR START:
> E025 Description: GLUE Schema object hierarchy violation
> E025 Affected DN: NA
> E025 Affected attribute: GLUE2Domain published
> E025 Published value: GLUE2Contact missing  
> 
> AssertionError: False is not true : WARNING START:
> W034 Description: Mandatory attribute not present
> W034 Affected DN: GLUE2DomainId=mysite.com 
>                   o=GLUE
> W034 Affected attribute: GLUE2DomainID
> W034 Published value: NA 
> 
> WARNING START:
> W034 Description: Mandatory attribute not present
> W034 Affected DN: GLUE2DomainId=mysite.com 
>                   o=GLUE
> W034 Affected attribute: GLUE2DomainName
> W034 Published value: NA
> ```
> 
> So errors due to missing `GLUE2Location` and `GLUE2Contact` attributes when object is a `GLUE2Domain`. But technically this is not in accordance with [GLUE 2.0](https://redmine.ogf.org/dmsf/glue-wg6ff7.html?folder_id=18) or the [GLUE 2.1 draft](https://docs.ogf.org/glue-2-1-test/): Screenshot 2023-03-23 at 17 24 58
> 
> But this was added on purpose to address a bug in an inaccessible bug tracker: [0aca90c](https://github.com/EGI-Federation/glue-validator/commit/0aca90cf144595088e00af4b6691a9a8bb1deb84)
> 
> So maybe we could add the missing objects to the tests, and document in the code that while it's breaking/not following the spec, it was added on purpose (even if we are not sure why, I guess it was making sense to ensure that we have a contact + location)?
> 
> And we could likely ignore the warnings.
> 
> @paolini78 any opinion on this?

I fixed some issues with the tests, so there are no warnings, still it complains about the non-mandatory in GLUE objects:
```
../bin/glue-validator -v 3 -f ldif/GLUE2AdminDomain/AdminDomain.ldif
CRITICAL - errors 2, warnings 0, info 0 | errors=2;warnings=0;info=0
AssertionError: False is not true : ERROR START:
E025 Description: GLUE Schema object hierarchy violation
E025 Affected DN: NA
E025 Affected attribute: GLUE2Domain published
E025 Published value: GLUE2Location missing

ERROR START:
E025 Description: GLUE Schema object hierarchy violation
E025 Affected DN: NA
E025 Affected attribute: GLUE2Domain published
E025 Published value: GLUE2Contact missing
```

**Comment by enolfc** [comment]
BTW, is the name of the attributes case sensitive? i.e. GlueDomainId vs GlueDomainID?

**Comment by gwarf** [comment]
> BTW, is the name of the attributes case sensitive? i.e. GlueDomainId vs GlueDomainID?

It seems so, in the [GFD147](https://github.com/OpenGridForum/redmine_dmsf_files/blob/main/GF/GFD.147b4d7.pdf?raw=true), in the section 3 General statements:
> The Information Model and its renderings MUST treat strings, both entity and attribute names and their values, as being case-sensitive

**Comment by gwarf** [comment]
So basically we should either be strict and follow the GLUE spec by the book, and revert the changes on the test of some attributes present for some specific objects, or keep it as it, with the validator throwing error for things that are not in the spec, assuming it was done for some unknown reason that is still valid.
I'm fine with following the spec, it seems to make sense for something like a validator.
@paolini78, any opinion?

**Comment by paolini78** [comment]
after a chat we realised that it is only the Site-BDII which publishes the GLUE2Domain object, with GLUE2Location and GLUE2Contact objects under it, and maybe this is the reason why in the specification the Location and Contact objects are optional (the compute and storage services don't need them), so please consider the Location and Contact objects compulsory if the GLUEDomain is published.

**Comment by enolfc** [comment]
don't want to lose this one:
image

**Review by enolfc — APPROVED** [review]
:+1: although I'm biased. 
Lot's of room for improvement anyway

**Comment by gwarf** [comment]
Perfect, thanks @enolfc !

**Pull request merged**
